---
abstract: 'Basic invocation of the test companion class engine'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-CompanionClasses
provides:
  Test::CompanionClasses:
    file: lib/Test/CompanionClasses.pm
    version: 1.100870
  Test::CompanionClasses::Base:
    file: lib/Test/CompanionClasses/Base.pm
    version: 1.100870
  Test::CompanionClasses::Engine:
    file: lib/Test/CompanionClasses/Engine.pm
    version: 1.100870
  Test::CompanionClasses::Engine_TEST:
    file: lib/Test/CompanionClasses/Engine_TEST.pm
    version: 1.100870
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  Data::Inherited: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Getopt::Long: 0
  Scalar::Util: 0
  Test::More: 0.88
  UNIVERSAL::require: 0
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-CompanionClasses
  homepage: http://search.cpan.org/dist/Test-CompanionClasses/
  repository: http://github.com/hanekomu/Test-CompanionClasses
version: 1.100870
