---
abstract: 'Basic invocation of Test::CompanionClasses::Engine'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-CompanionClasses
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Complex: 0
  Data::Inherited: 0
  Test::More: 0.94
  UNIVERSAL::require: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-CompanionClasses
  homepage: http://search.cpan.org/dist/Test-CompanionClasses/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/test-companionclasses.git
version: 0.06
